//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLens.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicLens.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Lens is an exclusive Lens App for Windows Phone that let you share the amazing photos you take adding the music you&apos;re listening at the moment. Plus, you can also add your position or current time in the picture. And on top of that, you can add some amazing filters provided by Nokia itself.
        ///
        ///If you have any questions regarding Music Lens, or you would love to have some new features, let me know writing at jcupi@outlook.com.
        ///
        ///Coming soon to Windows 8 as fast as possible! Thanks for downloading the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutPage_AboutTheApp {
            get {
                return ResourceManager.GetString("AboutPage_AboutTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPage_PivotAbout_Title {
            get {
                return ResourceManager.GetString("AboutPage_PivotAbout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string AboutPage_PivotLyrics_Title {
            get {
                return ResourceManager.GetString("AboutPage_PivotLyrics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string AboutPage_PivotPrivacy_Title {
            get {
                return ResourceManager.GetString("AboutPage_PivotPrivacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to.
        /// </summary>
        public static string AboutPage_PivotThx_Title {
            get {
                return ResourceManager.GetString("AboutPage_PivotThx_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On using your Location.
        ///- Music Lens does not store nor upload information about your location at any time.
        ///- Music Lens only uses your location, in an optional way, to obtain the street and city you&apos;re currently at, just so you can add that information as a label in your picture.
        ///.
        /// </summary>
        public static string AboutPage_PrivacyPolicy {
            get {
                return ResourceManager.GetString("AboutPage_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Explorer application demonstrates some of the image editing capabilities and performance of the Nokia Image Editing SDK by allowing you to apply a number of filter layers to existing or newly captured photos..
        /// </summary>
        public static string AboutPage_TextBlock_About {
            get {
                return ResourceManager.GetString("AboutPage_TextBlock_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics are provided by the awesome guys at LYRICSnMUSIC, the ultimate music search engine that also contains information about when your favorite band is touring and more cool stuff.
        ///
        ///Go check their website. If you&apos;re an indie artist and would like to see your lyrics appearing on LYRICSnMUSIC and of course on Music Lens, contact them.
        ///
        ///LYRICSnMUSIC, a lyric and music search engine for music people, by music people..
        /// </summary>
        public static string AboutPage_Textblock_Lyrics {
            get {
                return ResourceManager.GetString("AboutPage_Textblock_Lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Explorer version {0}.
        /// </summary>
        public static string AboutPage_TextBlock_Version {
            get {
                return ResourceManager.GetString("AboutPage_TextBlock_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Jedi master: Walter Novoa (@WarNov), if Music Lens has reached significant updates it&apos;s because of his humongous feedback! :) I&apos;m reaching the third major update in less than three weeks because of this great guy who works at Microsoft. You rock WarNov!.
        /// </summary>
        public static string AboutPage_ThxTo {
            get {
                return ResourceManager.GetString("AboutPage_ThxTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string App_About {
            get {
                return ResourceManager.GetString("App_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch! This is not available on the trial version. To buy Music Lens, press Ok, Press Cancel if you want to still use the trial version..
        /// </summary>
        public static string App_IsTrial {
            get {
                return ResourceManager.GetString("App_IsTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string App_Menu_About {
            get {
                return ResourceManager.GetString("App_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving image failed.
        /// </summary>
        public static string App_MessageBox_SaveFailed_Caption {
            get {
                return ResourceManager.GetString("App_MessageBox_SaveFailed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately saving the image failed. Would you mind trying again?.
        /// </summary>
        public static string App_MessageBox_SaveFailed_Message {
            get {
                return ResourceManager.GetString("App_MessageBox_SaveFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported image type.
        /// </summary>
        public static string App_MessageBox_UnsupportedImage_Caption {
            get {
                return ResourceManager.GetString("App_MessageBox_UnsupportedImage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the type of the image you selected is unsupported by this application..
        /// </summary>
        public static string App_MessageBox_UnsupportedImage_Message {
            get {
                return ResourceManager.GetString("App_MessageBox_UnsupportedImage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic from album.
        /// </summary>
        public static string App_PickAlbum {
            get {
                return ResourceManager.GetString("App_PickAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate me.
        /// </summary>
        public static string App_RateMe {
            get {
                return ResourceManager.GetString("App_RateMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a pic.
        /// </summary>
        public static string App_TakePic {
            get {
                return ResourceManager.GetString("App_TakePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Lens.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the lyrics for the song here..
        /// </summary>
        public static string EditPage_NoLyrics {
            get {
                return ResourceManager.GetString("EditPage_NoLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text settings.
        /// </summary>
        public static string EditPage_Title {
            get {
                return ResourceManager.GetString("EditPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick filter.
        /// </summary>
        public static string FilterPage_Title {
            get {
                return ResourceManager.GetString("FilterPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seriously? No music?.
        /// </summary>
        public static string Music_NoMusic_Artist {
            get {
                return ResourceManager.GetString("Music_NoMusic_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #NotPlayingAnything.
        /// </summary>
        public static string Music_NoMusic_NowPlaying {
            get {
                return ResourceManager.GetString("Music_NoMusic_NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Lens is Sad :(.
        /// </summary>
        public static string Music_NoMusic_Song {
            get {
                return ResourceManager.GetString("Music_NoMusic_Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near.
        /// </summary>
        public static string PhotoPage_Address {
            get {
                return ResourceManager.GetString("PhotoPage_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we couldn&apos;t get your location..
        /// </summary>
        public static string PhotoPage_Address_Error {
            get {
                return ResourceManager.GetString("PhotoPage_Address_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS is disabled on your phone..
        /// </summary>
        public static string PhotoPage_Address_GPSDisabled {
            get {
                return ResourceManager.GetString("PhotoPage_Address_GPSDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add filter.
        /// </summary>
        public static string PhotoPage_Button_AddFilter {
            get {
                return ResourceManager.GetString("PhotoPage_Button_AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save photo.
        /// </summary>
        public static string PhotoPage_Button_Save {
            get {
                return ResourceManager.GetString("PhotoPage_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share it.
        /// </summary>
        public static string PhotoPage_Button_Share {
            get {
                return ResourceManager.GetString("PhotoPage_Button_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get song.
        /// </summary>
        public static string PhotoPage_Button_StartMusic {
            get {
                return ResourceManager.GetString("PhotoPage_Button_StartMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved..
        /// </summary>
        public static string PhotoPage_Image_Saved {
            get {
                return ResourceManager.GetString("PhotoPage_Image_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string PhotoPage_Menu_Clear_Filters {
            get {
                return ResourceManager.GetString("PhotoPage_Menu_Clear_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show your location.
        /// </summary>
        public static string PhotoPage_Menu_Show_Address {
            get {
                return ResourceManager.GetString("PhotoPage_Menu_Show_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide your location.
        /// </summary>
        public static string PhotoPage_Menu_Show_Address_No {
            get {
                return ResourceManager.GetString("PhotoPage_Menu_Show_Address_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lyrics.
        /// </summary>
        public static string PhotoPage_Menu_Show_Lyrics {
            get {
                return ResourceManager.GetString("PhotoPage_Menu_Show_Lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide current lyrics.
        /// </summary>
        public static string PhotoPage_Menu_Show_Lyrics_No {
            get {
                return ResourceManager.GetString("PhotoPage_Menu_Show_Lyrics_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current time.
        /// </summary>
        public static string PhotoPage_Menu_Show_Time {
            get {
                return ResourceManager.GetString("PhotoPage_Menu_Show_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide current time.
        /// </summary>
        public static string PhotoPage_Menu_Show_Time_No {
            get {
                return ResourceManager.GetString("PhotoPage_Menu_Show_Time_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style it!.
        /// </summary>
        public static string PhotoPage_Menu_Text {
            get {
                return ResourceManager.GetString("PhotoPage_Menu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard current image?.
        /// </summary>
        public static string PhotoPage_MessageBox_Discard_Caption {
            get {
                return ResourceManager.GetString("PhotoPage_MessageBox_Discard_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current image has not been saved. Do you wish to discard the applied filters?
        ///
        ///Press ok to discard changes and go back to the camera roll stream. Press cancel to continue working with the current image..
        /// </summary>
        public static string PhotoPage_MessageBox_Discard_Message {
            get {
                return ResourceManager.GetString("PhotoPage_MessageBox_Discard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Check your Internet connection :(.
        /// </summary>
        public static string PhotoPage_NoInternet {
            get {
                return ResourceManager.GetString("PhotoPage_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find the lyrics :(.
        /// </summary>
        public static string PhotoPage_NoLyrics {
            get {
                return ResourceManager.GetString("PhotoPage_NoLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLIED FILTERS.
        /// </summary>
        public static string PhotoPage_TextBlock_Filters {
            get {
                return ResourceManager.GetString("PhotoPage_TextBlock_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PhotoPage_TextBlock_NoFilters {
            get {
                return ResourceManager.GetString("PhotoPage_TextBlock_NoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        public static string PhotoPage_Title {
            get {
                return ResourceManager.GetString("PhotoPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capture photo.
        /// </summary>
        public static string StreamPage_Button_Camera {
            get {
                return ResourceManager.GetString("StreamPage_Button_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick photo.
        /// </summary>
        public static string StreamPage_Button_Library {
            get {
                return ResourceManager.GetString("StreamPage_Button_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string StreamPage_Button_More {
            get {
                return ResourceManager.GetString("StreamPage_Button_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string StreamPage_Button_Refresh {
            get {
                return ResourceManager.GetString("StreamPage_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you&apos;re not listening to music right now, we&apos;ll start it for you..
        /// </summary>
        public static string StreamPage_NoMusic {
            get {
                return ResourceManager.GetString("StreamPage_NoMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow!!! You don&apos;t have music on your cellphone :(..
        /// </summary>
        public static string StreamPage_NoMusicOnPhone {
            get {
                return ResourceManager.GetString("StreamPage_NoMusicOnPhone", resourceCulture);
            }
        }
    }
}
